apiVersion: apps/v1
kind: Deployment
metadata:
  name: weatherservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: weather
  template:
    metadata:
      labels:
        app: weather
    spec:
      containers:
        - name: weatherservice
          image: public.ecr.aws/a5p8o7q9/weatherservice:v1
          ports:
            - containerPort: 8080
