apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather
spec:
  replicas: 2
  selector:
    matchLabels: # ReplicaSet이 제어해야 하는 파드를 결정
      app: weather
  template:
    metadata:
      labels:
        app: weather # pod 의 label
    spec:
      containers:
        - name: weather
          image: public.ecr.aws/a5p8o7q9/weatherservice:v65 # ECR의 image
          ports:
            - containerPort: 8080 # container 의 port
