apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: weather
spec:
  ingress:
    - path: /weather
      backend:
        serviceName: weatherservice
        servicePort: 8080
