apiVersion: apps/v1
kind: Deployment
metadata:
  name: tour
spec:
  replicas: 2
  selector:
    matchLabels: # ReplicaSet이 제어해야 하는 파드를 결정
      app: tour
  template:
    metadata:
      labels:
        app: tour # pod 의 label
    spec:
      containers:
        - name: tour
          image: public.ecr.aws/a5p8o7q9/tourservice:v19 # ECR의 image
          ports:
            - containerPort: 8080 # container 의 port
          volumeMounts:
            - name: tour-log
              mountPath: /var/log/pods # Mount the volume to the container's file system
      volumes:
        - name: tour-log
          hostPath:
            path: /var/log/pods # Mount the volume to the host file system