apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: air
resources:
  - deploy.yml
  - service.yml
ingress:
  - path: /air
    backend:
      serviceName: airservice
      servicePort: 8090
