{{- range $app := .Values.applications }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $app.name }}-deployment
spec:
  replicas: {{ $app.replicas }}
  selector:
    matchLabels:
      app: {{ $app.name }}
  template:
    metadata:
      labels:
        app: {{ $app.name }}
    spec:
      containers:
        - name: {{ $app.name }}
          image: {{ $app.container.image.repository }}:{{ $app.container.image.tag }}
          ports:
            - containerPort: {{ $app.container.port }}
{{- end }}