{{- range $application := .Values.applications }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $application.name }}-deployment
spec:
  replicas: {{ $application.replicas }}
  selector:
    matchLabels:
      app: {{ $application.name }}
  template:
    metadata:
      labels:
        app: {{ $application.name }}
    spec:
      containers:
        - name: {{ $application.name }}
          image: {{ $application.image.repository }}:{{$application.image.tag}}
          ports:
            - containerPort: {{ $application.port }}
{{- end }}