{{- range $app := .Values.applications }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $app.name }}-service
spec:
  selector:
    app: {{ $app.name }}
  ports:
    - name: http
      port: {{ $app.servicePort }}
      targetPort: {{ $app.container.port }}
{{- end }}
