{{- range $app := .Values.applications }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}-service
spec:
  selector:
    app: {{ .name }}
  ports:
    - name: http
      port: {{ .servicePort }}
      targetPort: {{ .port }}
{{- end }}
